export { default } from './Apac'
export { default as Information } from './subpages/information'
export { default as NormalSentence } from './subpages/normal-sentence'
export { default as SimpleSentence } from './subpages/simple-sentence'
export { default as Word } from './subpages/word'
