name: Auto Deploy to Develop Server
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Deploy-Websol-Client-And-Docz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Install project dependencies    
        run: npm install
      - name: Build Websol
        run: npm run dev-build
      - name: Deploy Websol
        run: aws s3 rm s3://hbrc-dev-new-apac/ --recursive && aws s3 cp dist s3://hbrc-dev-new-apac --recursive
